name: Push to Forked

on:
  push:
    branches:
      - main

jobs:
  push-to-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.FORK_PAT }}
          ref: main
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name zuzokim
          git config user.email zuzokim@gmail.com
          git remote add forked https://zuzokim:${FORK_PAT}@github.com/zuzokim/sqetchclub-frontend.git

      - name: Push to forked
        run: |
          git push forked main:main

      - name: Clean up  
        run: |
          git remote remove forked